#!perl
use strict;
use warnings;
use App::CPANPermission;
use App::CPANPermission::Table;

my $module = shift || '-h';
die "Usage: $0 MODULE\n" if $module =~ /^(-h|--help)$/;

my ($res, $err) = App::CPANPermission->new->get_permission_for($module);
die "$err\n" unless $res;

my @permission = @{$res->{permission}};
die "Not found\n" if @permission == 1 and !$permission[0]{owner};

print "distribution: @{[$res->{distfile} || 'undef']}\n\n";
my $table = App::CPANPermission::Table->new(qw(module_name owner co_maintainers));
for my $perm (@permission) {
    my @co = @{ $perm->{co_maintainers} || [] };
    my $co = @co ? join(",", @co) : 'undef';
    $table->add($perm->{module_name}, $perm->{owner} || 'undef', $co);
}
print $table->stringify;
